import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database types
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: 'Admin' | 'Member';
          permissions: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          full_name: string;
          role?: 'Admin' | 'Member';
          permissions?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: 'Admin' | 'Member';
          permissions?: string[];
          updated_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          whatsapp?: string;
          instagram?: string;
          since: string;
          status: string;
          client_type: string;
          last_contact: string;
          portal_access_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone: string;
          whatsapp?: string;
          instagram?: string;
          since?: string;
          status?: string;
          client_type?: string;
          last_contact?: string;
          portal_access_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          whatsapp?: string;
          instagram?: string;
          since?: string;
          status?: string;
          client_type?: string;
          last_contact?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          project_name: string;
          client_id: string;
          project_type: string;
          package_id?: string;
          add_ons: any[];
          date: string;
          deadline_date?: string;
          location: string;
          progress: number;
          status: string;
          active_sub_statuses: string[];
          total_cost: number;
          amount_paid: number;
          payment_status: string;
          team: any[];
          notes?: string;
          accommodation?: string;
          drive_link?: string;
          client_drive_link?: string;
          final_drive_link?: string;
          start_time?: string;
          end_time?: string;
          image?: string;
          revisions: any[];
          promo_code_id?: string;
          discount_amount?: number;
          shipping_details?: string;
          dp_proof_url?: string;
          printing_details: any[];
          printing_cost?: number;
          transport_cost?: number;
          is_editing_confirmed_by_client: boolean;
          is_printing_confirmed_by_client: boolean;
          is_delivery_confirmed_by_client: boolean;
          confirmed_sub_statuses: string[];
          client_sub_status_notes: Record<string, string>;
          sub_status_confirmation_sent_at: Record<string, string>;
          completed_digital_items: string[];
          invoice_signature?: string;
          custom_sub_statuses: any[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_name: string;
          client_id: string;
          project_type: string;
          package_id?: string;
          add_ons?: any[];
          date: string;
          deadline_date?: string;
          location: string;
          progress?: number;
          status?: string;
          active_sub_statuses?: string[];
          total_cost?: number;
          amount_paid?: number;
          payment_status?: string;
          team?: any[];
          notes?: string;
          accommodation?: string;
          drive_link?: string;
          client_drive_link?: string;
          final_drive_link?: string;
          start_time?: string;
          end_time?: string;
          image?: string;
          revisions?: any[];
          promo_code_id?: string;
          discount_amount?: number;
          shipping_details?: string;
          dp_proof_url?: string;
          printing_details?: any[];
          printing_cost?: number;
          transport_cost?: number;
          is_editing_confirmed_by_client?: boolean;
          is_printing_confirmed_by_client?: boolean;
          is_delivery_confirmed_by_client?: boolean;
          confirmed_sub_statuses?: string[];
          client_sub_status_notes?: Record<string, string>;
          sub_status_confirmation_sent_at?: Record<string, string>;
          completed_digital_items?: string[];
          invoice_signature?: string;
          custom_sub_statuses?: any[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_name?: string;
          client_id?: string;
          project_type?: string;
          package_id?: string;
          add_ons?: any[];
          date?: string;
          deadline_date?: string;
          location?: string;
          progress?: number;
          status?: string;
          active_sub_statuses?: string[];
          total_cost?: number;
          amount_paid?: number;
          payment_status?: string;
          team?: any[];
          notes?: string;
          accommodation?: string;
          drive_link?: string;
          client_drive_link?: string;
          final_drive_link?: string;
          start_time?: string;
          end_time?: string;
          image?: string;
          revisions?: any[];
          promo_code_id?: string;
          discount_amount?: number;
          shipping_details?: string;
          dp_proof_url?: string;
          printing_details?: any[];
          printing_cost?: number;
          transport_cost?: number;
          is_editing_confirmed_by_client?: boolean;
          is_printing_confirmed_by_client?: boolean;
          is_delivery_confirmed_by_client?: boolean;
          confirmed_sub_statuses?: string[];
          client_sub_status_notes?: Record<string, string>;
          sub_status_confirmation_sent_at?: Record<string, string>;
          completed_digital_items?: string[];
          invoice_signature?: string;
          custom_sub_statuses?: any[];
          updated_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          name: string;
          whatsapp?: string;
          contact_channel: string;
          location: string;
          status: string;
          date: string;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          whatsapp?: string;
          contact_channel: string;
          location: string;
          status?: string;
          date?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          whatsapp?: string;
          contact_channel?: string;
          location?: string;
          status?: string;
          date?: string;
          notes?: string;
          updated_at?: string;
        };
      };
      client_feedback: {
        Row: {
          id: string;
          client_name: string;
          rating: number;
          satisfaction: string;
          feedback: string;
          date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_name: string;
          rating: number;
          satisfaction: string;
          feedback: string;
          date?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_name?: string;
          rating?: number;
          satisfaction?: string;
          feedback?: string;
          date?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          user_id: string | null;
          company_name: string;
          full_name: string;
          email: string;
          phone: string;
          website: string | null;
          address: string | null;
          bank_account: string | null;
          authorized_signer: string | null;
          bio: string | null;
          briefing_template: string | null;
          terms_and_conditions: string | null;
          income_categories: any;
          expense_categories: any;
          project_types: any;
          event_types: any;
          asset_categories: any;
          sop_categories: any;
          project_status_config: any;
          notification_settings: any;
          security_settings: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          company_name: string;
          full_name: string;
          email: string;
          phone: string;
          website?: string | null;
          address?: string | null;
          bank_account?: string | null;
          authorized_signer?: string | null;
          bio?: string | null;
          briefing_template?: string | null;
          terms_and_conditions?: string | null;
          income_categories?: any;
          expense_categories?: any;
          project_types?: any;
          event_types?: any;
          asset_categories?: any;
          sop_categories?: any;
          project_status_config?: any;
          notification_settings?: any;
          security_settings?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          company_name?: string;
          full_name?: string;
          email?: string;
          phone?: string;
          website?: string | null;
          address?: string | null;
          bank_account?: string | null;
          authorized_signer?: string | null;
          bio?: string | null;
          briefing_template?: string | null;
          terms_and_conditions?: string | null;
          income_categories?: any;
          expense_categories?: any;
          project_types?: any;
          event_types?: any;
          asset_categories?: any;
          sop_categories?: any;
          project_status_config?: any;
          notification_settings?: any;
          security_settings?: any;
          updated_at?: string;
        };
      };
    };
  };
}